# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvstore.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvstore.Store')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='value',
            unique_together=set([('store', 'key')]),
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set([('id', 'store')]),
        ),
    ]
